apiVersion: v1
kind: Service
metadata:
  name: gopal-prod-1
  namespace: default
spec:
  type: NodePort        
  selector:
    app: gopal-bg-1
  ports:
  - port: 80
    targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: gopal-preview-1
  namespace: default
spec:
  type: NodePort       
  selector:
    app: gopal-bg-1
  ports:
  - port: 80
    targetPort: 8081