apiVersion: v1
kind: Service
metadata:
  name: gopal-prod
  namespace: default
spec:
  type: NodePort        
  selector:
    app: gopal-bg
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gopal-preview
  namespace: default
spec:
  type: NodePort       
  selector:
    app: gopal-bg
  ports:
  - port: 80
    targetPort: 8080